### PR TITLE
Compute time successors for all possible increments of the node

### LINKED ISSUE #165: Missing time successor leads to wrong successor node
Consider the following example:
robot_cropped

With the ATA that has the following transition, among others:
```
(⊤ U (!(camera_on()) ∧ grasping())) → {grasping()} → ⊤
```

The successor node in the bottom right satisfies `!(camera_on()) ∧ grasping()` and the parent contains the following word:
```
drive(machine1, machine2), 2) | (boot_camera(), 3), (shutdown_camera(), 3), ((⊤ U (!(camera_on()) ∧ grasping())), 3)
```

Therefore, the bottom right successor should have a word that contains no ATA configuration. However, this word is missing.  This is because the clocks in the parent (above) only have has one clock that is not maxed and therefore does not have a third time successor (we stop computing time successor if all clocks are in the max region).

However, we still need the time successor with increment 3, because a different word in the node causes a time successor with increment 3. Therefore, we cannot compute the time successors for each word specifically, but instead need to consider all words of a node.

### PR DESCRIPTION
**Pull request by morxa**
If a node contains a word that already only contains clocks in the maximal region, then it only has a single time successors, because there is no increment that changes the successor. However, the node may have another word with more time successors.  When computing the successor nodes, we also need to consider the first word, even for a higher time increment. Otherwise, the successor of the first word is missing from the successor node.

The second part fixes a related but more general problem:
When computing the time successor for a node, we need to
consider all canonical words in the node. Parts of this was fixed in the first part (28e054f8b3ff4811e53ed876fbaae64b7b6e17be), however, that fix is incomplete. As an example, consider a
node with two words:
1. `{ (l0, c, 1) }`
2. `{ (ATA, 0) }, { (l0, c, 1) }`

Then the first time successor of (2) increments the clock of the ATA but
not of the TA. However, in word (1), there is no ATA component to
increment. Therefore, the time successor with increment 1 must be the
same word. To compute these time successors correctly, we first compute
the time successors of each word. We then check if there is any word
where the reg_a does not change. If that is the case, then we need to
keep the original word for any word where the time successor has a
change reg_a.

Fixes #165.

### CODE REVIEW

File: src/search/include/search/synchronous_product.h [hunk 1]
```diff
@@ -254,4 +246,67 @@ get_time_successors(const CanonicalABWord<Location, ConstraintSymbolType> &canon
 	return time_successors;
 }
```
Comment (modass) [inline src/search/include/search/synchronous_product.h:248]:
```suggestion
/** Compute the direct time successors which introduce an increment in the ATA configuration for each of the passed words.
 * @param canonical_words The set of canonical words to compute time successors of
 * @param K The maximal constant
 * @return All direct time successors of the passed words
 */
```

**Review by modass — APPROVED** [review]
The changes look good to me, approved!
